import { type NextPage } from "next";
import * as React from "react";

import BackgroundParticles from "@/components/BackgroundParticles";
import Head from "next/head";
import clsx from "clsx";
import { useEffect, useState } from "react";
import { InformationCircleIcon } from "@heroicons/react/24/solid";
import { useRouter } from "next/router";
import { Transition } from "@headlessui/react";

const Home: NextPage = () => {
  const [windowHeight, setWindowHeight] = useState(0);
  const [show, setShow] = useState(false);

  const router = useRouter();

  useEffect(() => {
    setWindowHeight(window.innerHeight);
    setShow(true);
  }, []);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className="">
        <div className="flex min-h-screen w-full flex-col items-center p-4 pt-20 text-center">
          <h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl md:text-6xl">
            <span className="block xl:inline">Data to enrich your</span>
            <span className="block text-indigo-600 xl:inline">
              online business
            </span>
          </h1>
          <p className="mx-auto mt-3 max-w-md text-base text-gray-500 sm:text-lg md:mt-5 md:max-w-3xl md:text-xl">
            Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui
            lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat
            fugiat aliqua.
          </p>
          <div className="mx-auto mt-5 max-w-md sm:flex sm:justify-center md:mt-8">
            <div className="rounded-md shadow">
              <a
                href="#"
                className="flex w-full items-center justify-center rounded-md border border-transparent bg-indigo-600 px-8 py-3 text-base font-medium text-white hover:bg-indigo-700 md:py-4 md:px-10 md:text-lg"
              >
                Get started
              </a>
            </div>
            <div className="mt-3 rounded-md shadow sm:mt-0 sm:ml-3">
              <a
                href="#"
                className="flex w-full items-center justify-center rounded-md border border-transparent bg-white px-8 py-3 text-base font-medium text-indigo-600 hover:bg-gray-50 md:py-4 md:px-10 md:text-lg"
              >
                Live demo
              </a>
            </div>
          </div>
        </div>
      </main> */}
      <main>
        <BackgroundParticles />
        <Transition
          show={show}
          enter="transition-opacity duration-1000"
          enterFrom="opacity-0"
          enterTo="opacity-100"
        >
          <div className="flex min-h-screen w-full flex-col items-center justify-center p-4 text-center">
            <h1
              className={clsx(
                windowHeight < 540 ? "mt-12" : "",
                "max-w-2xl text-4xl font-bold text-gray-800 sm:text-5xl md:text-6xl"
              )}
            >
              Une vision à 360° pour faire décoller vos projets 🚀
            </h1>
            <br />

            <h2 className="max-w-5xl text-lg text-gray-800 sm:text-xl md:text-2xl">
              Avec mon profil international et mon expérience entrepreneuriale
              en tant que développeur web, je peux vous aider à voir
              l&apos;ensemble du tableau dans les détails et ainsi minimiser les
              risques d&apos;échecs à toute étape de votre projet.
            </h2>
            <br />
            <button
              onClick={() => router.push("/about")}
              className="inline-flex items-center rounded-full bg-gray-800 py-3 px-5 font-bold text-white transition delay-75 ease-in-out hover:translate-y-1 hover:scale-110 hover:bg-gray-700 active:scale-95"
            >
              <InformationCircleIcon className="mr-2 h-5 w-5" />
              <span>En savoir plus</span>
            </button>
          </div>
        </Transition>
      </main>
    </>
  );
};

export default Home;
